Naseembr
Mellanox/ngc_multinode_perf pull request #16
Opened 2023-08-09 21:47 UTC by nshamshoum

2023-08-13 08:45 UTC, blochl requested changes

2023-08-13 08:45 UTC, blochl commented on ngc_rdma_test.sh
> +    ms_size_time=("-s" "${1}" "-D" "3")
Is the duration reduction on purpose?

2023-08-13 08:45 UTC, blochl commented on ngc_rdma_test.sh
> +set -x
Why the debug setting is turned on?

2023-08-13 08:45 UTC, blochl commented on ngc_rdma_test.sh
> +    ms_size_time=("-s" "${PKT_SIZE}" "-D" "10")
In the previous commit the duration was reduced to 3 seconds (was that on purpose?) and here it is restored to 10 again?

2023-08-13 08:45 UTC, blochl commented on ngc_rdma_test.sh
> +        ssh "${CLIENT_IP}" "numactl -C ${CLIENT2_CORE} ${TEST} -d ${CLIENT_DEVICES[1]} --report_gbit ${ms_size_time[*]} -b ${SERVER_IP} -F -q4 -p 10001 ${client_cuda} --out_json --out_json_file=/tmp/
Th `.json` suffix is missing here. Was it tested?

2023-08-13 08:45 UTC, blochl commented on ngc_rdma_test.sh
> +		PASS=1
Isn't it better to just return 1 or 0, instead of relying on a variable?

2023-08-13 08:45 UTC, blochl commented on ngc_rdma_test.sh
> +BW_PASS_RATE="$(awk "BEGIN {printf \"%.0f\n\", 2*0.9*${port_rate}}")"
Is changing the output format (rounding to integer) intentional here and couple of lines below?

2023-08-13 08:45 UTC, blochl commented on common.sh
> +    LINE=$(ssh "${SERVER_TRUSTED}" "nvidia-smi topo -mp" | grep -w "${NICX}" | grep "${RELATION}" )
Should `nvidia-utils` be added to the list of dependencies in README, now that it's being used?

2023-08-13 08:45 UTC, blochl commented on ngc_rdma_test.sh
> +    for n in {22..23}
Why only 4 and 8 MB now??

2023-08-13 08:45 UTC, blochl commented on ngc_rdma_test.sh
> +
There should not be a separate commit for removing debugs. They should just not be in a commit to begin with. You can just not stage them for a commit when you do it.

2023-08-13 08:45 UTC, blochl commented on ngc_rdma_test.sh
> +    for n in {1..23}
Please ammend the previous commit to fix that. The PR is not merged yet, so you can fix previous commits. No commit should knowingly introduce a new bug.

2023-08-14 10:46 UTC, ErezAshkenazi commented on ngc_rdma_test.sh
> +        RUN_WITH_CUDA=0
shouldn't RUN_WITH_CUDA=1 at this stage?

2023-08-15 07:06 UTC, nshamshoum commented on ngc_rdma_test.sh
> +BW_PASS_RATE="$(awk "BEGIN {printf \"%.0f\n\", 2*0.9*${port_rate}}")"
Yes, will need to comper integers.

2023-08-15 07:08 UTC, nshamshoum commented on common.sh
> +    LINE=$(ssh "${SERVER_TRUSTED}" "nvidia-smi topo -mp" | grep -w "${NICX}" | grep "${RELATION}" )
Need to add nvidia-utiles to README since this requirement was added recently, will update README

2023-08-15 07:08 UTC, nshamshoum commented on ngc_rdma_test.sh
> +
You are right.

2023-08-15 07:11 UTC, nshamshoum commented on ngc_rdma_test.sh
> +        RUN_WITH_CUDA=0
Bash True is represented as 0 - so this why it is set to 0 and not 1.

2023-08-15 07:14 UTC, nshamshoum commented on ngc_rdma_test.sh
> +        ssh "${CLIENT_IP}" "numactl -C ${CLIENT2_CORE} ${TEST} -d ${CLIENT_DEVICES[1]} --report_gbit ${ms_size_time[*]} -b ${SERVER_IP} -F -q4 -p 10001 ${client_cuda} --out_json --out_json_file=/tmp/
you are right - this was tested on a single port and not on 2

2023-08-15 08:16 UTC, blochl approved these changes
Thanks for the changes, @nshamshoum !

2023-08-17 12:08 UTC, merged