functionality to pick connection types with a list
Mellanox/ngc_multinode_perf pull request #42
Opened 2023-12-05 15:28 UTC by RazGavrieli

Added a flag to pick connection types with a list. (rdma)

usage: 
./ngc_rdma_test <client> <clientadapters> <server> <serveradapters> --conn=UC,RC,XRC
only commas, no spaces (same convention as mlx adapters)

edge cases:
- Using both --all_connection_types and --conn together, would just enter the condition in line 280 and skip the "else" in 284 that handles --conn. 
- different connection types may be available (line 43), in future will append use get_perftest_connect_options() function on all tests to append all connection types into a list.

2023-12-05 19:05 UTC, blochl requested changes

2023-12-05 19:05 UTC, blochl commented on ngc_rdma_test.sh
> +VALID_CONN_TYPES=("RC" "XRC" "UC" "UD" "DC")
Currently the valid connection types are sourced from the `--help` command of each test (as not all the tests support all the commands). Is there a reason to change it?

2023-12-05 19:05 UTC, blochl commented on ngc_rdma_test.sh
> +Syntax: $0 <client hostname> <client ib device1>[,client ib device2] <server hostname> <server ib device1>[,server ib device2] [--use_cuda] [--qp=<num of QPs>] [--all_connection_types]/[-conn=<list o
You forgot a dash here.

Also, please add this doc to README.

2023-12-05 19:05 UTC, blochl commented on ngc_rdma_test.sh
>  Syntax: $0 <client hostname> <client ib device1>[,client ib device2] <server hostname> <server ib device1>[,server ib device2] [--use_cuda] [--qp=<num of QPs>] [--all_connection_types]/[-conn=<list o
There should NOT be a "clean up for [_sic._] pullrequest" commit! If you want this functionality in the original commit, just amend it (or squash the two). You don't want a commit which makes things dirty, and then another one which makes things clean in the Git tree.

2023-12-05 19:18 UTC, closed without merging

2023-12-05 19:21 UTC, RazGavrieli commented on ngc_rdma_test.sh
>  Syntax: $0 <client hostname> <client ib device1>[,client ib device2] <server hostname> <server ib device1>[,server ib device2] [--use_cuda] [--qp=<num of QPs>] [--all_connection_types]/[-conn=<list o
thx for the feedback. instead of creating a mess and then cleaning it up, I will get to work on cleaner commits and raise a new PR soon. Thanks

2023-12-06 14:23 UTC, blochl commented on ngc_rdma_test.sh
>  Syntax: $0 <client hostname> <client ib device1>[,client ib device2] <server hostname> <server ib device1>[,server ib device2] [--use_cuda] [--qp=<num of QPs>] [--all_connection_types]/[-conn=<list o
No need for a new PR! You can just force-push your commits to the same branch, and it will update the current PR. :smiley:

2023-12-06 14:26 UTC, RazGavrieli commented on ngc_rdma_test.sh
>  Syntax: $0 <client hostname> <client ib device1>[,client ib device2] <server hostname> <server ib device1>[,server ib device2] [--use_cuda] [--qp=<num of QPs>] [--all_connection_types]/[-conn=<list o
Cool. Didn't know that. I already closed the PR before force-pushing to undo the last commits..