Add capability to specify a list of connection types for rdma tests
Mellanox/ngc_multinode_perf pull request #43
Opened 2023-12-05 20:28 UTC by RazGavrieli

usage:
./ngc_rdma_test --conn=UC,RC,XRC
only commas, no spaces (same convention as mlx adapters)

2023-12-06 15:05 UTC, blochl commented on ngc_rdma_test.sh
> +            connection_types=($(comm -12 <(printf '%s\n' "${available_conn_types[@]}" | LC_ALL=C sort) <(printf '%s\n' "${connection_types[@]}" | LC_ALL=C sort)))
Clever. :smiley:

2023-12-06 19:03 UTC, blochl commented
Thanks for the fixes! Although as I wrote before, let's not create a dirty commit and clean afterwards. This is a single commit, as it introduces a single feature. Please squash the "fixing" commits with the "actual" one before we merge. (Then force-push, and it will update the same PR - no need for a new PR).

2023-12-10 15:10 UTC, blochl commented on ngc_rdma_test.sh
> +    if ! $exists_for_at_least_one_test; then
Please use `if [ "${exists_for_at_least_one_test}" != "true" ]` for that. What you did here will result in an error, or worse yet - in an arbitrary command execution, if `exists_for_at_least_one_test` gets an unexpected value.

For example:
```bash
$ exists_for_at_least_one_test="foo"
$ if ! $exists_for_at_least_one_test; then
> echo "false"
> fi
Command 'foo' not found
```
Now imagine if it were `rm -rf ...` instead of `foo`. And yes, currently I see it can only be `true` or `false`, but this way it's safer and more future proof.

2023-12-10 15:10 UTC, blochl commented on ngc_rdma_test.sh
> -
I'd keep this empty line, it makes the text clearer.

2023-12-19 13:54 UTC, RazGavrieli commented on common.sh
> -                suffix="${NC} - expected ${port_rate}Gb/s"
moved to line 862. originally suffix was empty (${NC}) and included the port_rate only if failed.

2023-12-19 16:25 UTC, blochl requested changes
@RazGavrieli , thanks for your changes!
Please address the following issues though:
1. In the last commit you have included some changes which belong to previous commits. Please amend the previous commits instead.
2. Please rebase on the latest main branch - currently there are conflicts.

Otherwise looks fine, thanks!!

2023-12-19 16:25 UTC, blochl commented on common.sh
> +        passing_port_rate="$(awk "BEGIN {printf \"%.0f\n\", 0.9*${port_rate}}")"
This belongs to the previous commit.

2023-12-19 16:25 UTC, blochl commented on common.sh
> +            if [ $(echo "$BW < ${passing_port_rate}" | bc) -ne 0 ]
This belongs to the previous commit.

2023-12-19 16:25 UTC, blochl commented on common.sh
> +            if [ $(echo "$BW < ${passing_port_rate}" | bc) -ne 0 ] || [ $(echo "$S_BW < ${passing_port_rate}" | bc) -ne 0 ]
This belongs to the previous commit.

2023-12-19 16:25 UTC, blochl commented on ngc_rdma_test.sh
> +        if [[ "$available_conn_types" == *"$CONN_TYPE"* ]]; then
This belongs to the first commit ion this series.

2023-12-19 16:25 UTC, blochl commented on ngc_rdma_test.sh
> +    if [ "${exists_for_at_least_one_test}" != "true" ]; then
This belongs to the first commit ion this series.

2023-12-20 14:03 UTC, blochl approved these changes
Thanks a lot, @RazGavrieli !

2023-12-20 15:02 UTC, merged