Ipsec compatibility
Mellanox/ngc_multinode_perf pull request #5
Opened 2021-05-11 16:42 UTC by DorKovachi

*IPsec unaware configuration added
*IPsec test added

2021-05-13 21:16 UTC, amirancel commented on README.md
> +* Relevant for BlueField2 devices
Fix to BlueField-2 DPUs

2021-05-13 21:17 UTC, amirancel commented on README.md
> +* Will configure IPsec unaware mode on both client and server BlueField2 and then run TCP test
We call it "full offload" not unaware

2021-05-13 21:20 UTC, amirancel commented on ipsec_full_offload_setup.sh
> +LOCAL_BF_IP=192.168.1.64  #default
You can't have default IP, it will never be used. it is configured by the administrator

2021-05-13 21:23 UTC, amirancel commented on ipsec_full_offload_setup.sh
> +	sshpass -p ${SSHPASSW} ssh -l root ${bf_name} /bin/bash << 'EOF'
Who gives the password ?
Should be changed to have passwordless ssh

2021-05-13 21:23 UTC, amirancel commented on ipsec_full_offload_setup.sh
> +devlink dev eswitch set pci/0000:03:00.0 mode switchdev
This means we support only running on port 0, port 1 will not work, need to add to readme

2021-05-13 21:25 UTC, amirancel commented on ipsec_full_offload_setup.sh
> +ssh ${CLIENT_TRUSTED} systemctl restart openibd
Why do you need to restart the driver ?

2021-05-13 21:26 UTC, amirancel commented on ngc_ipsec_unaware_tcp_test.sh
> +#!/bin/bash
replace "unaware" by "full_offload"

2021-05-13 21:28 UTC, amirancel commented on ngc_ipsec_unaware_tcp_test.sh
> +bash ./ngc_tcp_test.sh ${CLIENT_TRUSTED} ${CLIENT_DEVICE} ${SERVER_TRUSTED} ${SERVER_DEVICE}
New test usage requires duplex flag and change_mtu flag
bash ./ngc_tcp_test.sh ${CLIENT_TRUSTED} ${CLIENT_DEVICE} ${SERVER_TRUSTED} ${SERVER_DEVICE} HALF DONT_CHANGE

2021-05-13 21:29 UTC, amirancel requested changes
see my change requests

2021-05-18 08:03 UTC, DorKovachi commented on README.md
> +* Will configure IPsec unaware mode on both client and server BlueField2 and then run TCP test
changed

2021-05-18 08:05 UTC, DorKovachi commented on ipsec_full_offload_setup.sh
> +LOCAL_BF_IP=192.168.1.64  #default
removed.
there is code after the function to get the IP.

2021-05-18 08:24 UTC, DorKovachi commented on ipsec_full_offload_setup.sh
> +devlink dev eswitch set pci/0000:03:00.0 mode switchdev
added.
will add more support further down the line.

2021-05-18 08:50 UTC, DorKovachi commented on ngc_ipsec_unaware_tcp_test.sh
> +#!/bin/bash
ack

2021-05-18 10:18 UTC, DorKovachi commented on ngc_ipsec_unaware_tcp_test.sh
> +bash ./ngc_tcp_test.sh ${CLIENT_TRUSTED} ${CLIENT_DEVICE} ${SERVER_TRUSTED} ${SERVER_DEVICE}
ack

2021-05-31 09:08 UTC, DorKovachi commented on ipsec_full_offload_setup.sh
> +ssh ${CLIENT_TRUSTED} systemctl restart openibd
omited

2021-05-31 10:52 UTC, DorKovachi commented
attended to said issues, please review again

2021-06-14 11:19 UTC, amirancel approved these changes

2021-06-14 11:21 UTC, amirancel approved these changes

2021-06-14 11:24 UTC, merged