RDMA: Enable multiple port testing
Mellanox/ngc_multinode_perf pull request #60
Opened 2024-01-22 10:13 UTC by RoiZilberzwaig

2024-01-22 14:21 UTC, blochl requested changes

2024-01-22 14:21 UTC, blochl commented on ngc_rdma_test.sh
> +# If so, the script calls to show_help function to display help or usage information.
The above is kinda self-evident, no? :) ([Self-documenting code](https://swimm.io/learn/documentation-tools/tips-for-creating-self-documenting-code) is awesome)

2024-01-22 14:21 UTC, blochl commented on ngc_rdma_test.sh
> +BASE_TCP_POTR=10000
s/POTR/PORT/

2024-01-22 14:21 UTC, blochl commented on ngc_rdma_test.sh
> +        fatal "The number of server and client devices must be equal."
Indentation.

2024-01-22 14:21 UTC, blochl commented on ngc_rdma_test.sh
> +done
Please re-add the newline.

2024-01-23 07:54 UTC, RoiZilberzwaig commented on ngc_rdma_test.sh
> +# If so, the script calls to show_help function to display help or usage information.
Fixed!

2024-01-23 07:54 UTC, RoiZilberzwaig commented on ngc_rdma_test.sh
> +BASE_TCP_POTR=10000
Fixed!

2024-01-23 07:54 UTC, RoiZilberzwaig commented on ngc_rdma_test.sh
> +        fatal "The number of server and client devices must be equal."
Fixed!

2024-01-23 07:54 UTC, RoiZilberzwaig commented on ngc_rdma_test.sh
> +done
Fixed!

2024-01-23 07:56 UTC, RoiZilberzwaig commented
Thanks Leonid!
All comments you voted on have been fixed.

2024-01-23 09:41 UTC, blochl approved these changes
Thanks, @RoiZilberzwaig! Awesome work!

2024-01-24 07:53 UTC, merged