ngc_rdma: Add internal loopback script
Mellanox/ngc_multinode_perf pull request #70
Opened 2024-02-06 09:21 UTC by RavidRothfeld

2024-02-06 11:48 UTC, blochl commented on ngc_internal_lp_rdma_wrapper.sh
> +    ssh "${SERVER_IP}" dmidecode -t 0 |grep -i version | awk '{$1=$1};1' | sed 's/^/BIOS /' &>> "${LOGFILE}"
One ssh:
```bash
"sudo dmidecode -t 0,1" | sed -n -e '/^BIOS/,/^$/ s/^[[:space:]]*\(Version\)/BIOS \1/p' -e '/^System/,/^$/ s/^[[:space:]]*\(Serial\|Product\)/\1/p'
```

2024-02-06 20:18 UTC, blochl requested changes

2024-02-06 20:18 UTC, blochl commented on ngc_rdma_wrapper.sh
> +    results_wrapper
This won't work. I know you fix it later, but no commit should introduce a bug. Please fix it.

2024-02-06 20:18 UTC, blochl commented on ngc_rdma_wrapper.sh
> +    results_wrapper "cuda"
This won't work. I know you fix it later, but no commit should introduce a bug. Please fix it.

2024-02-06 20:18 UTC, blochl commented on common.sh
> +     awk "NR >= ${start_line}" "${LOGFILE}"| while IFS= read -r line; do
Indentation.

2024-02-06 20:18 UTC, blochl commented on ngc_rdma_wrapper.sh
> +    ssh "${SERVER_IP}" sudo dmidecode -t 0 | grep -i version | awk '{$1=$1};1' | sed 's/^/BIOS /' &>> "${LOGFILE}"
This deserves a separate commit - completely unrelated to your commit, and is an important change (the sudo part, not the space).

2024-02-06 20:18 UTC, blochl commented on ngc_rdma_wrapper.sh
> +    readarray -t SERVER_MLNX <<< "$(ssh "${SERVER_IP}" "sudo mst status -v"  | awk '/mlx/{print $3 " " $4}' | sort -t ' ' -k2,2V)"
This deserves a separate commit - completely unrelated to your commit, and is an important change (the sudo part, not the space).

2024-02-06 20:18 UTC, blochl commented on ngc_internal_lb_rdma_wrapper.sh
> +    while true; do
Maybe add max trials, instead of an infinite loop? Say after 3 times of neither [yYnN] exit with failure.

2024-02-06 20:18 UTC, blochl commented on ngc_internal_lb_rdma_wrapper.sh
> +        ngc_rdma_internal_lp
Indentation

2024-02-06 20:18 UTC, blochl commented on ngc_internal_lb_rdma_wrapper.sh
> +#!/bin/bash
In this series, you add this file, then remove it, then add it again? Please add it only once.

2024-02-07 11:06 UTC, blochl commented on common.sh
> -# Display results (taken from the logfile, used for the wrapper scripts)
Change wrapper_results functionality ?
Also - change how and why: please write in the commit message.

2024-02-07 12:18 UTC, RavidRothfeld commented on common.sh
> -# Display results (taken from the logfile, used for the wrapper scripts)
I've explained in the commit msg.
For some reason, it won't show up here.

2024-02-07 13:30 UTC, merged